run:
  go: "1.25"
linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - gofmt
    - goimports
    - ineffassign
    - errcheck
    - revive
    - stylecheck
    - unused
    - dupl
    - gocritic
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
issues:
  exclude-use-default: false
  exclude:
    - "should have comment or be unexported"
  exclude-rules:
    - linters: [revive]
      text: "package-comments"
    - linters: [stylecheck]
      text: "ST1000"
  max-issues-per-linter: 0
  max-same-issues: 0
